- name: SHOW TRUNK STATUS
  hosts: ios
  gather_facts: no
  connection: local
  tasks:

    - name: SHOW ISDN STATUS
      ios_command:
        commands:
          - show isdn status
        wait_for: result[0] contains ISDN
        username: "{{ un }}"
        host: "{{ inventory_hostname }}"
      register: result
    - debug:
        var: result
